name: example
description: Charts-Flutter Demo
environment:
  sdk: ">=2.17.0"

dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.1.1
  intl: "0.18.1"
flutter:
  uses-material-design: true
dev_dependencies:
  build_runner: ^2.1.11
